<?php

namespace MSJFramework\Services;

use Illuminate\Support\Facades\DB;

class SeederGeneratorService
{
    /**
     * Generate seeder untuk menu yang baru dibuat
     */
    public function generateMenuSeeder(array $menuData): string
    {
        $timestamp = date('Ymd_His');
        $dmenu = $menuData['dmenu'];
        $className = "MSJMenu_{$dmenu}_{$timestamp}_Seeder";
        
        // Get data dari database
        $gmenuData = DB::table('sys_gmenu')->where('gmenu', $menuData['gmenu'])->first();
        $dmenuData = DB::table('sys_dmenu')->where('dmenu', $dmenu)->first();
        $authData = DB::table('sys_auth')->where('dmenu', $dmenu)->get();
        $tableData = DB::table('sys_table')->where('dmenu', $dmenu)->get();
        
        $content = $this->buildMenuSeederContent($className, $gmenuData, $dmenuData, $authData, $tableData);
        
        $path = base_path("database/seeders/{$className}.php");
        file_put_contents($path, $content);
        
        return $path;
    }

    /**
     * Generate seeder untuk enum yang baru dibuat
     */
    public function generateEnumSeeder(string $idenum): string
    {
        $timestamp = date('Ymd_His');
        $safeName = str_replace(['_', '-'], '', $idenum);
        $className = "MSJEnum_{$safeName}_{$timestamp}_Seeder";
        
        // Get data dari database
        $enumData = DB::table('sys_enum')->where('idenum', $idenum)->get();
        
        $content = $this->buildEnumSeederContent($className, $idenum, $enumData);
        
        $path = base_path("database/seeders/{$className}.php");
        file_put_contents($path, $content);
        
        return $path;
    }

    protected function buildMenuSeederContent($className, $gmenuData, $dmenuData, $authData, $tableData): string
    {
        $gmenuArray = $this->objectToArrayString($gmenuData);
        $dmenuArray = $this->objectToArrayString($dmenuData);
        
        $authArrayStr = "[\n";
        foreach ($authData as $auth) {
            $authArrayStr .= "            " . $this->objectToArrayString($auth) . ",\n";
        }
        $authArrayStr .= "        ]";
        
        $tableArrayStr = "[\n";
        foreach ($tableData as $table) {
            $tableArrayStr .= "            " . $this->objectToArrayString($table) . ",\n";
        }
        $tableArrayStr .= "        ]";

        return <<<PHP
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by MSJ Framework
 * Menu: {$dmenuData->name} ({$dmenuData->dmenu})
 * Generated at: {$this->now()}
 */
class {$className} extends Seeder
{
    public function run(): void
    {
        \$this->command->info('📦 Seeding menu: {$dmenuData->name}...');
        
        \$dmenu = '{$dmenuData->dmenu}';
        \$gmenu = '{$dmenuData->gmenu}';
        
        // Check if gmenu exists, if not insert
        if (!DB::table('sys_gmenu')->where('gmenu', \$gmenu)->exists()) {
            DB::table('sys_gmenu')->insert({$gmenuArray});
        }
        
        // Delete existing dmenu data (cascade)
        DB::table('sys_auth')->where('dmenu', \$dmenu)->delete();
        DB::table('sys_table')->where('dmenu', \$dmenu)->delete();
        DB::table('sys_dmenu')->where('dmenu', \$dmenu)->delete();
        
        // Insert dmenu
        DB::table('sys_dmenu')->insert({$dmenuArray});
        
        // Insert auth
        \$authData = {$authArrayStr};
        if (!empty(\$authData)) {
            DB::table('sys_auth')->insert(\$authData);
        }
        
        // Insert table config
        \$tableData = {$tableArrayStr};
        if (!empty(\$tableData)) {
            DB::table('sys_table')->insert(\$tableData);
        }
        
        \$this->command->info('✓ Menu {$dmenuData->name} seeded successfully!');
    }
}
PHP;
    }

    protected function buildEnumSeederContent($className, $idenum, $enumData): string
    {
        $enumArrayStr = "[\n";
        foreach ($enumData as $enum) {
            $enumArrayStr .= "            " . $this->objectToArrayString($enum) . ",\n";
        }
        $enumArrayStr .= "        ]";

        return <<<PHP
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Auto-generated by MSJ Framework
 * Enum: {$idenum}
 * Generated at: {$this->now()}
 */
class {$className} extends Seeder
{
    public function run(): void
    {
        \$this->command->info('📦 Seeding enum: {$idenum}...');
        
        \$idenum = '{$idenum}';
        
        // Delete existing enum data
        DB::table('sys_enum')->where('idenum', \$idenum)->delete();
        
        // Insert enum data
        \$enumData = {$enumArrayStr};
        
        if (!empty(\$enumData)) {
            DB::table('sys_enum')->insert(\$enumData);
        }
        
        \$this->command->info('✓ Enum {$idenum} seeded successfully!');
    }
}
PHP;
    }

    protected function objectToArrayString($obj): string
    {
        if (!$obj) return '[]';
        
        $arr = (array) $obj;
        $parts = [];
        
        foreach ($arr as $key => $value) {
            if ($value === null) {
                $parts[] = "'{$key}' => null";
            } elseif (is_numeric($value) && !is_string($value)) {
                $parts[] = "'{$key}' => {$value}";
            } else {
                $escaped = addslashes($value);
                $parts[] = "'{$key}' => '{$escaped}'";
            }
        }
        
        return '[' . implode(', ', $parts) . ']';
    }
    
    protected function now(): string
    {
        return date('Y-m-d H:i:s');
    }
}
